version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: promo_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_IMPORT_FILES_STRATEGY: OVERWRITE_EXISTING
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json
    command: ["start-dev", "--import-realm", "--log-level=DEBUG"]

  backend:
    build:
      context: ./promocodemanagementsystem
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/promo_system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      DEFAULT_TENANT: tenant1
      # Add other backend env vars as needed
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - keycloak

  frontend:
    build:
      context: ./promo-code-management-ui
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data: