server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/promo_system?currentSchema=tenant1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: tenant1
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/promo-realm
          jwk-set-uri: http://localhost:8081/realms/promo-realm/protocol/openid-connect/certs

keycloak:
  client-id: promo-management
  client-secret: dev-secret

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.jdbc: DEBUG
    org.springframework.transaction: DEBUG