server:
  port: 8082

spring:
  cache:
    cache-names: promo-codes, promo-code-search
    caffeine:
      spec: maximumSize=500,expireAfterAccess=3600s
  datasource:
    url: jdbc:postgresql://localhost:5432/promo_system?currentSchema=tenant1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DEFAULT_TENANT} # Use environment variable DEFAULT_TENANT to set the default tenant
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/promo-realm
          jwk-set-uri: http://keycloak:8080/realms/promo-realm/protocol/openid-connect/certs

keycloak:
  client-id: promo-management
  client-secret: ${KEYCLOAK_CLIENT_SECRET} # Use environment variable KEYCLOAK_CLIENT_SECRET to set the secret

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.jdbc: DEBUG
    org.springframework.transaction: DEBUG